apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orderflow.fullname" . }}-config
  labels:
    {{- include "orderflow.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.environment.ENVIRONMENT | quote }}
  LOG_LEVEL: {{ .Values.environment.LOG_LEVEL | quote }}
  PYTHONDONTWRITEBYTECODE: "1"
